namespace: "alikins"
name: "collection_reqs_missing_test"
version: "2.3.5"
description: "a collection with requirements.yml that has unsolveable reqs"
authors: ["Adrian Likins"]
license: "GPL-3.0-or-later"
dependencies:
  - geerlingguy.ntp
